### ISSUE TITLE
Source of firmware

### ISSUE THREAD

**Issue by OParczyk** [r1me/TapeXUM#1]
Hello

This is a really neat project!
Could you please release the source code of the firmware?
Further I have difficulty finding the code for the firmware this is based on, could you give me a link?

Thanks!

**Comment by heneault** [comment]
That would be great to have the sources to port to other types of Arduino and other OS like Linux and Mac

**Comment by r1me** [comment]
> Could you please release the source code of the firmware?
> Further I have difficulty finding the code for the firmware this is based on, could you give me a link?

Hey, this project is based on ZoomTape, a part of OpenCBM package. A modified OpenCBM can be found in my other repo, TapeXUM firmware is there:
https://github.com/r1me/OpenCBM/tree/master/xum1541
`make MODEL=PROMICRO_TAPE build`
