### ISSUE TITLE
What is behind this crazy idea of use 0.1 uF electrolytic capacitor?

### ISSUE THREAD

**Issue by mesmariusz** [r1me/TapeXUM#2]
Hi :-)

What is behind this crazy idea of use 0.1 uF electrolytic capacitor?
[https://i.imgur.com/Gs0jLsC.png](https://i.imgur.com/Gs0jLsC.png) 
[https://i.imgur.com/7Lc5MwK.png](https://i.imgur.com/7Lc5MwK.png)

Why didn't you use just standard unpolarized capacitor e.g. 100 nF / 50V ?

Is there seriously any reason to use 0.1 uF electrolytic capacitor?

**Comment by mesmariusz** [comment]
Anybody here?

May I use just common unpolarised 100nF instead of electrolytic 0.1 uF ?

**Comment by r1me** [comment]
Indeed it's just a bypass capacitor for 5V line, I might change it to a non-polar in later revision (if it ever happens).

**Comment by mesmariusz** [comment]
Ok, thank you very much for your feedback.
