### ISSUE TITLE
Available .hex vs Pro-Micro-ATmega32U4-5-V-16-MHz - should it work on this hardware ?

### ISSUE THREAD

**Issue by mesmariusz** [r1me/TapeXUM#3]
Should the firmware:
https://github.com/r1me/TapeXUM/tree/main/firmware

work with this module:
https://shopee.pl/Baipestotoy-Pro-Micro-ATmega32U4-5-V-16-MHz-Wymie%C5%84-ATmega328-Arduino-Pro-Mini-i.550891774.12958189188

Is / should be the uC on this module compatibile with this .hex ?

**Comment by r1me** [comment]
Hey, yes that's a right footprint Arduino Pro Micro (there are few other versions that wouldn't fit). The one you've linked will work correctly for this project.
