### ISSUE TITLE
Any recommended way to flash .hex file to Arduino Pro Micro (Leonardo) ?

### ISSUE THREAD

**Issue by mesmariusz** [r1me/TapeXUM#4]
Hi.

Is there any recommended way to program .hex file to Arduino Pro Micro (Leonardo) ?

I have the issue as below:

https://i.imgur.com/XYd78Y6.png

**Comment by r1me** [comment]
`avrdude -p m32u4 -c avr109 -P comX -U flash:w:xum1541-PROMICRO_TAPE-v08.hex`
