### ISSUE TITLE
9VDC power supply seems too high

### ISSUE THREAD

**Issue by Kalidomra** [r1me/TapeXUM#7]
The BOM lists a 9VDC power supply. The schematic shows 6VDC. Which is the correct supply voltage?

**Comment by r1me** [comment]
Hi, motor power part of TapeXUM design resembles the C64 schematic in which a 9V goes through a 6.8V zener diode, thus delivering slightly above 6V to a datasette motor. A 9VDC power supply connected to TapeXUM is used to create that voltage in exact same manner.
